### ISSUE TITLE
Icons are not appear on Dark Menu Bar

### ISSUE THREAD

**Issue by se** [geraldoramos/crypto-bar#12]
It is impossible to see icons on Dark Menu Bar.

![image](https://user-images.githubusercontent.com/491844/34172105-eb21ca76-e501-11e7-8d53-dbeed56a9ca2.png)

I have forked your project. I will try to do that change and pull request ASAP ;-)

Great project btw ^^ Thank you.

**Comment by geraldoramos** [comment]
Oh, didn't think about that!

It would be awesome if you have the chance to get it fixed. I will put on my list as well in case you can't do it.

Thanks for reporting!

**Comment by CocoaPriest** [comment]
+1

**Comment by se** [comment]
I have fixed it at #13. I hope it helps 😉

**Comment by geraldoramos** [comment]
Thanks @se, PR accepted.
