### ISSUE TITLE
Need a thousand separator

### ISSUE THREAD

**Issue by benju69** [geraldoramos/crypto-bar#17]

**Comment by geraldoramos** [comment]
Working on a new version right now, this will be fixed and many other things.

![image](https://user-images.githubusercontent.com/5693297/34316159-6de01b38-e74c-11e7-8818-6f20949e0a06.png)

**Comment by geraldoramos** [comment]
the new version is available as a draft [here:](
https://github.com/geraldoramos/crypto-bar/releases/tag/untagged-07966bd54df8de58ad3c)

Master branch is now carrying the new updates which fix this thread issue. The draft release is not published yet. Users will not get updates for it until it gets published as final.
