### ISSUE TITLE
I can't start it using "npm start".

### ISSUE THREAD

**Issue by ultimate1352** [geraldoramos/crypto-bar#2]
I'm newbie on Electron.

As your README.md mention, start commend is "npm install & npm start".
But I can't start it.

Finally, I started your app using below.

![2017-12-18 11 43 08](https://user-images.githubusercontent.com/4495200/34111509-47bc5e32-e44d-11e7-8d10-aae3fd9c7dff.png)

**Comment by geraldoramos** [comment]
sorry, my bad. Didn't include it as a start script!

You can run using `electron .` if you have electron installed globally
