### ISSUE TITLE
Add a way to add/remove coins

### ISSUE THREAD

**Issue by lucasbento** [geraldoramos/crypto-bar#20]
First of all, thank you for building it, it's really nice!

Currently the list is in fixed size and there's no way to keep `coins.length !== 6`, it would be nice to have a way to add and/or remove coins.

**Comment by geraldoramos** [comment]
Thanks, @lucasbento, will look into a good solution for that.

**Comment by geraldoramos** [comment]
@lucasbento fixed this in the new [release](https://github.com/geraldoramos/crypto-bar/releases/latest)

**Comment by lucasbento** [comment]
@geraldoramos: nice, thanks!
