### ISSUE TITLE
Awkward updating as of now

### ISSUE THREAD

**Issue by vladdoster** [geraldoramos/crypto-bar#21]
Hello, 

Do you have any plans to introduce **auto-updater**? If not I can work on an elegant solution.

Cheers,
Vlad

**Comment by geraldoramos** [comment]
Hi Vlad,

 I've implemented an auto-updater using electron-updater (part of electron builder). I created a routine to check for updates every 30s and if detects one, it will download it and notify the user when finished with a notification saying it will be installed upon exit. In the UI It shows that an update is available and ask the user to restart (in the footer, close to the app name/version). I initially created a link where the user clicks and app restarts, but for some reason, it was not working in production, only in dev. I left it for now but was planning to get back to it.

Unfortunately, I had some issues with the update in the beginning (and it was not working at all) but I fixed it. I've been testing it carefully in the last 2 releases and it seems to be working fine. What issue did you have? Do you know what version you were once you had the issue?

What changes do you envision to make it better? I would love any help to make the app better in any way.

Thanks a lot!

**Comment by geraldoramos** [comment]
Will close this, for now. Let me know if you have any input on what should be improved in the update flow.
