### ISSUE TITLE
Hyper Key + D Opens Dev Tools

### ISSUE THREAD

**Issue by r3volution11** [geraldoramos/crypto-bar#24]
As the title says, Hyper (Command + Control + Option + Shift) + D opens the developer tools in the app. After doing so the only way to close the tools is to pop them out into their own window and close.

I have this shortcut set up for Dash which I use throughout the day. This is really starting to bug me. :grin:

**Comment by geraldoramos** [comment]
Thanks, I will add this to my list. The idea is to not have any global shortcuts.

**Comment by geraldoramos** [comment]
This has been fixed.
