### ISSUE TITLE
UX improvement 

### ISSUE THREAD

**Issue by wwong18** [geraldoramos/crypto-bar#32]
Rather than having to go into activity monitor and quitting the widget itself, I suggest adding a 'quit' button. 

Maybe also bring back notifications and alerts?

**Comment by awatertrevi** [comment]
@wwong18 You can also press CMD + Q when you're in the widget.

**Comment by wongww** [comment]
@awatertrevi but just for usability, I think most people have found that having a 'Quit' button in the widget menu is quite helpful because not everyone might know the command. But you're right, Cmd + Q does work.
