### ISSUE TITLE
CMD+D shortcut

### ISSUE THREAD

**Issue by antho1404** [geraldoramos/crypto-bar#9]
When pressing CMD+D it open a window with the version but the version is already in the menu and more important it's a shortcut for the whole desktop so it intercept the shortcut from another application. For exemple on Visual Code CMD+D select the next occurence of the selected word and this now open the version of crypto bar. 

This shortcut should be removed or if really necessary customisable

**Comment by geraldoramos** [comment]
I'm aware. This will be fixed in the next release. I plan to submit one tonight or tomorrow before noon.

**Comment by antho1404** [comment]
awesome :)

**Comment by geraldoramos** [comment]
done @antho1404, finished before I expected. New release with the fix to this issue here and some other new stuff is up! Just need a restart to update (PS: Next releases will have a "new version available alert" that will trigger a restart if the user press it.)

**Comment by antho1404** [comment]
great that was really fast :) I will update right now good app by the way, simple and efficient

**Comment by geraldoramos** [comment]
thanks! @antho1404
